2024-04-26 23:03:39,162 __main__ (lichess-bot.py:1051) INFO 
    .   _/|
    .  // o\
    .  || ._)  lichess-bot 2024.3.21.1
    .  //__\
    .  )___(   Play on Lichess with a bot
    
2024-04-26 23:03:39,179 lib.config (config.py:262) DEBUG Config:
token: logger
url: https://lichess.org/
engine:
  dir: ./engines/
  name: ExampleEngine
  working_dir: ''
  protocol: homemade
  ponder: true
  polyglot:
    enabled: false
    book:
      standard:
      - engines/book1.bin
      - engines/book2.bin
    min_weight: 1
    selection: weighted_random
    max_depth: 20
  draw_or_resign:
    resign_enabled: false
    resign_score: -1000
    resign_for_egtb_minus_two: true
    resign_moves: 3
    offer_draw_enabled: true
    offer_draw_score: 0
    offer_draw_for_egtb_zero: true
    offer_draw_moves: 10
    offer_draw_pieces: 10
  online_moves:
    max_out_of_book_moves: 10
    max_retries: 2
    chessdb_book:
      enabled: false
      min_time: 20
      move_quality: good
      min_depth: 20
    lichess_cloud_analysis:
      enabled: false
      min_time: 20
      move_quality: best
      max_score_difference: 50
      min_depth: 20
      min_knodes: 0
    lichess_opening_explorer:
      enabled: false
      min_time: 20
      source: masters
      player_name: ''
      sort: winrate
      min_games: 10
    online_egtb:
      enabled: false
      min_time: 20
      max_pieces: 7
      source: lichess
      move_quality: best
  lichess_bot_tbs:
    syzygy:
      enabled: false
      paths:
      - engines/syzygy
      max_pieces: 7
      move_quality: best
    gaviota:
      enabled: false
      paths:
      - engines/gaviota
      max_pieces: 5
      min_dtm_to_consider_as_wdl_1: 120
      move_quality: best
  homemade_options: null
  uci_options:
    Move Overhead: 100
    Threads: 4
    Hash: 512
    SyzygyPath: ./syzygy/
    UCI_ShowWDL: true
  silence_stderr: false
abort_time: 30
fake_think_time: false
rate_limiting_delay: 0
move_overhead: 2000
quit_after_all_games_finish: false
correspondence:
  move_time: 60
  checkin_period: 300
  disconnect_time: 150
  ponder: false
challenge:
  concurrency: 5
  sort_by: first
  accept_bot: true
  only_bot: false
  max_increment: 20
  min_increment: 0
  max_base: 1800
  min_base: 0
  max_days: 14
  min_days: 1
  variants:
  - standard
  time_controls:
  - bullet
  - blitz
  - rapid
  - classical
  modes:
  - casual
  - rated
  bullet_requires_increment: false
greeting:
  hello: Hi! I'm Kyle's Chess AI. Good luck!
  goodbye: Good game, thanks for playing! If you haven't read the paper yet, please
    consider giving it a read.
  hello_spectators: Hi! I'm {me}. Type !help for a list of commands I can respond
    to.
  goodbye_spectators: Thanks for watching!
matchmaking:
  allow_matchmaking: false
  allow_during_games: false
  challenge_variant: random
  challenge_timeout: 30
  challenge_initial_time:
  - 60
  - 180
  challenge_increment:
  - 1
  - 2
  rating_preference: none
  opponent_allow_tos_violation: false
  challenge_mode: random
  challenge_filter: none

2024-04-26 23:03:39,181 lib.config (config.py:263) DEBUG ====================
2024-04-26 23:03:39,186 lib.config (config.py:262) DEBUG Config:
token: logger
url: https://lichess.org/
engine:
  dir: ./engines/
  name: ExampleEngine
  working_dir: C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot
  protocol: homemade
  ponder: true
  polyglot:
    enabled: false
    book:
      standard:
      - engines/book1.bin
      - engines/book2.bin
    min_weight: 1
    selection: weighted_random
    max_depth: 20
  draw_or_resign:
    resign_enabled: false
    resign_score: -1000
    resign_for_egtb_minus_two: true
    resign_moves: 3
    offer_draw_enabled: true
    offer_draw_score: 0
    offer_draw_for_egtb_zero: true
    offer_draw_moves: 10
    offer_draw_pieces: 10
  online_moves:
    max_out_of_book_moves: 10
    max_retries: 2
    chessdb_book:
      enabled: false
      min_time: 20
      move_quality: good
      min_depth: 20
    lichess_cloud_analysis:
      enabled: false
      min_time: 20
      move_quality: best
      max_score_difference: 50
      min_depth: 20
      min_knodes: 0
    lichess_opening_explorer:
      enabled: false
      min_time: 20
      source: masters
      player_name: ''
      sort: winrate
      min_games: 10
    online_egtb:
      enabled: false
      min_time: 20
      max_pieces: 7
      source: lichess
      move_quality: best
    max_depth: .inf
  lichess_bot_tbs:
    syzygy:
      enabled: false
      paths:
      - engines/syzygy
      max_pieces: 7
      move_quality: best
    gaviota:
      enabled: false
      paths:
      - engines/gaviota
      max_pieces: 5
      min_dtm_to_consider_as_wdl_1: 120
      move_quality: best
  homemade_options: null
  uci_options:
    Move Overhead: 100
    Threads: 4
    Hash: 512
    SyzygyPath: ./syzygy/
    UCI_ShowWDL: true
  silence_stderr: false
  uci_ponder: false
abort_time: 30
fake_think_time: false
rate_limiting_delay: 0
move_overhead: 2000
quit_after_all_games_finish: false
correspondence:
  move_time: 60
  checkin_period: 300
  disconnect_time: 150
  ponder: false
  uci_ponder: false
challenge:
  concurrency: 5
  sort_by: first
  accept_bot: true
  only_bot: false
  max_increment: 20
  min_increment: 0
  max_base: 1800
  min_base: 0
  max_days: 14
  min_days: 1
  variants:
  - standard
  time_controls:
  - bullet
  - blitz
  - rapid
  - classical
  modes:
  - casual
  - rated
  bullet_requires_increment: false
  block_list: []
  allow_list: []
greeting:
  hello: Hi! I'm Kyle's Chess AI. Good luck!
  goodbye: Good game, thanks for playing! If you haven't read the paper yet, please
    consider giving it a read.
  hello_spectators: Hi! I'm {me}. Type !help for a list of commands I can respond
    to.
  goodbye_spectators: Thanks for watching!
matchmaking:
  allow_matchmaking: false
  allow_during_games: false
  challenge_variant: random
  challenge_timeout: 30
  challenge_initial_time:
  - 60
  - 180
  challenge_increment:
  - 1
  - 2
  rating_preference: none
  opponent_allow_tos_violation: false
  challenge_mode: random
  challenge_filter: none
  block_list: []
  challenge_days:
  - null
  opponent_min_rating: 600
  opponent_max_rating: 4000
  overrides: {}
pgn_file_grouping: game

2024-04-26 23:03:39,186 lib.config (config.py:263) DEBUG ====================
2024-04-26 23:03:39,186 __main__ (lichess-bot.py:1054) INFO Checking engine configuration ...
2024-04-26 23:03:40,651 matplotlib (__init__.py:350) DEBUG matplotlib data path: C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\matplotlib\mpl-data
2024-04-26 23:03:40,655 matplotlib (__init__.py:350) DEBUG CONFIGDIR=C:\Users\Kyle_Remote\.matplotlib
2024-04-26 23:03:40,656 matplotlib (__init__.py:1511) DEBUG interactive is False
2024-04-26 23:03:40,657 matplotlib (__init__.py:1512) DEBUG platform is win32
2024-04-26 23:03:40,737 matplotlib (__init__.py:350) DEBUG CACHEDIR=C:\Users\Kyle_Remote\.matplotlib
2024-04-26 23:03:40,738 matplotlib.font_manager (font_manager.py:1574) DEBUG Using fontManager instance from C:\Users\Kyle_Remote\.matplotlib\fontlist-v330.json
2024-04-26 23:03:42,513 lib.engine_wrapper (engine_wrapper.py:68) DEBUG Starting engine: ['C:\\Users\\Kyle_Remote\\Documents\\Programs\\DS3ML3_Final_Project\\lichess-bot\\engines\\ExampleEngine']
2024-04-26 23:03:42,513 __main__ (lichess-bot.py:1057) INFO Engine configuration OK
2024-04-26 23:03:42,518 urllib3.connectionpool (connectionpool.py:1055) DEBUG Starting new HTTPS connection (1): lichess.org:443
2024-04-26 23:03:43,028 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/token/test HTTP/1.1" 200 None
2024-04-26 23:03:43,126 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "GET /api/account HTTP/1.1" 200 None
2024-04-26 23:03:43,126 __main__ (lichess-bot.py:1066) INFO Welcome KS_ChessAI!
2024-04-26 23:03:43,129 __main__ (lichess-bot.py:225) INFO You're now connected to https://lichess.org/ and awaiting challenges.
2024-04-26 23:03:43,641 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "GET /api/account/playing HTTP/1.1" 200 17
2024-04-26 23:03:52,085 __main__ (lichess-bot.py:404) DEBUG Event: {'type': 'challenge', 'challenge': {'id': 'pfNdLM2r', 'url': 'https://lichess.org/pfNdLM2r', 'status': 'created', 'challenger': {'id': 'checkyle', 'name': 'ChecKyle', 'rating': 1667, 'title': None, 'provisional': True, 'online': True, 'lag': 4}, 'destUser': {'id': 'ks_chessai', 'name': 'KS_ChessAI', 'rating': 2000, 'title': 'BOT', 'provisional': True, 'online': True}, 'variant': {'key': 'standard', 'name': 'Standard', 'short': 'Std'}, 'rated': False, 'speed': 'rapid', 'timeControl': {'type': 'clock', 'limit': 420, 'increment': 10, 'show': '7+10'}, 'color': 'random', 'finalColor': 'white', 'perf': {'icon': '\ue017', 'name': 'Rapid'}}, 'compat': {'bot': True, 'board': True}}
2024-04-26 23:03:52,085 __main__ (lichess-bot.py:455) INFO Accept Rapid casual challenge from ChecKyle (1667?) (pfNdLM2r)
2024-04-26 23:03:52,192 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/challenge/pfNdLM2r/accept HTTP/1.1" 200 11
2024-04-26 23:03:52,193 __main__ (lichess-bot.py:274) INFO --- Process Queued. Count: 1. IDs: {'pfNdLM2r'}
2024-04-26 23:03:52,194 __main__ (lichess-bot.py:404) DEBUG Event: {'type': 'gameStart', 'game': {'fullId': 'pfNdLM2rlr7w', 'gameId': 'pfNdLM2r', 'fen': 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', 'color': 'black', 'lastMove': '', 'source': 'friend', 'status': {'id': 20, 'name': 'started'}, 'variant': {'key': 'standard', 'name': 'Standard'}, 'speed': 'rapid', 'perf': 'rapid', 'rated': False, 'hasMoved': False, 'opponent': {'id': 'checkyle', 'username': 'ChecKyle', 'rating': 1667}, 'isMyTurn': False, 'secondsLeft': 420, 'compat': {'bot': True, 'board': True}, 'id': 'pfNdLM2r'}}
2024-04-26 23:03:52,194 __main__ (lichess-bot.py:274) INFO --- Process Used. Count: 1. IDs: {'pfNdLM2r'}
2024-04-26 23:03:52,202 urllib3.connectionpool (connectionpool.py:1055) DEBUG Starting new HTTPS connection (1): lichess.org:443
2024-04-26 23:03:52,713 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "GET /api/bot/game/stream/pfNdLM2r HTTP/1.1" 200 None
2024-04-26 23:03:52,713 __mp_main__ (lichess-bot.py:605) DEBUG Initial state: {'id': 'pfNdLM2r', 'variant': {'key': 'standard', 'name': 'Standard', 'short': 'Std'}, 'speed': 'rapid', 'perf': {'name': 'Rapid'}, 'rated': False, 'createdAt': 1714187032154, 'white': {'id': 'checkyle', 'name': 'ChecKyle', 'title': None, 'rating': 1667, 'provisional': True}, 'black': {'id': 'ks_chessai', 'name': 'KS_ChessAI', 'title': 'BOT', 'rating': 2000, 'provisional': True}, 'initialFen': 'startpos', 'clock': {'initial': 420000, 'increment': 10000}, 'type': 'gameFull', 'state': {'type': 'gameState', 'moves': '', 'wtime': 420000, 'btime': 420000, 'winc': 10000, 'binc': 10000, 'status': 'started'}}
2024-04-26 23:03:54,129 matplotlib (__init__.py:350) DEBUG matplotlib data path: C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\matplotlib\mpl-data
2024-04-26 23:03:54,134 matplotlib (__init__.py:350) DEBUG CONFIGDIR=C:\Users\Kyle_Remote\.matplotlib
2024-04-26 23:03:54,135 matplotlib (__init__.py:1511) DEBUG interactive is False
2024-04-26 23:03:54,135 matplotlib (__init__.py:1512) DEBUG platform is win32
2024-04-26 23:03:54,208 matplotlib (__init__.py:350) DEBUG CACHEDIR=C:\Users\Kyle_Remote\.matplotlib
2024-04-26 23:03:54,210 matplotlib.font_manager (font_manager.py:1574) DEBUG Using fontManager instance from C:\Users\Kyle_Remote\.matplotlib\fontlist-v330.json
2024-04-26 23:03:56,023 lib.engine_wrapper (engine_wrapper.py:68) DEBUG Starting engine: ['C:\\Users\\Kyle_Remote\\Documents\\Programs\\DS3ML3_Final_Project\\lichess-bot\\engines\\ExampleEngine']
2024-04-26 23:03:56,024 __mp_main__ (lichess-bot.py:611) DEBUG The engine for game pfNdLM2r has pid=?
2024-04-26 23:03:56,024 __mp_main__ (lichess-bot.py:614) INFO +++ https://lichess.org/pfNdLM2r/black Rapid vs ChecKyle (1667?) (pfNdLM2r)
2024-04-26 23:03:56,024 __mp_main__ (lichess-bot.py:725) DEBUG Game state: {'type': 'gameState', 'moves': 'e2e4', 'wtime': 420000, 'btime': 420000, 'winc': 10000, 'binc': 10000, 'status': 'started'}
2024-04-26 23:03:56,025 lib.conversation (conversation.py:86) INFO *** https://lichess.org/pfNdLM2r/black [player] KS_ChessAI: Hi! I'm Kyle's Chess AI. Good luck!
2024-04-26 23:03:56,027 urllib3.connectionpool (connectionpool.py:1055) DEBUG Starting new HTTPS connection (2): lichess.org:443
2024-04-26 23:03:56,549 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/pfNdLM2r/chat HTTP/1.1" 200 11
2024-04-26 23:03:56,550 lib.conversation (conversation.py:86) INFO *** https://lichess.org/pfNdLM2r/black [spectator] KS_ChessAI: Hi! I'm KS_ChessAI. Type !help for a list of commands I can respond to.
2024-04-26 23:03:56,651 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/pfNdLM2r/chat HTTP/1.1" 200 11
2024-04-26 23:03:56,651 __mp_main__ (lichess-bot.py:716) INFO 
2024-04-26 23:03:56,651 __mp_main__ (lichess-bot.py:717) INFO move: 1
2024-04-26 23:03:56,652 lib.engine_wrapper (engine_wrapper.py:687) INFO Searching for time 10 seconds for game pfNdLM2r
2024-04-26 23:03:56,653 backoff (_common.py:105) INFO Backing off play_game(...) for 0.3s (TypeError: EvalNet.forward() takes 2 positional arguments but 3 were given)
2024-04-26 23:03:56,654 lib.lichess (lichess.py:63) DEBUG Backing off 0.3 seconds after 1 tries calling function <function play_game at 0x000001D7B326C680> with args () and kwargs {'li': <lib.lichess.Lichess object at 0x000001D7B3265990>, 'control_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c0a90>, 'user_profile': {'id': 'ks_chessai', 'username': 'KS_ChessAI', 'perfs': {'bullet': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'blitz': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'rapid': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'classical': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'correspondence': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}}, 'title': 'BOT', 'createdAt': 1711486329716, 'seenAt': 1714186489523, 'playTime': {'total': 18282, 'tv': 0}, 'url': 'https://lichess.org/@/KS_ChessAI', 'count': {'all': 120, 'rated': 0, 'ai': 0, 'draw': 11, 'drawH': 11, 'loss': 92, 'lossH': 92, 'win': 17, 'winH': 17, 'bookmark': 0, 'playing': 0, 'import': 0, 'me': 0}, 'followable': True, 'following': False, 'blocking': False, 'followsYou': False}, 'config': <lib.config.Configuration object at 0x000001D7B32C2290>, 'challenge_queue': <ListProxy object, typeid 'list' at 0x1d7b32c88d0>, 'correspondence_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c8b10>, 'logging_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c8d50>, 'game_id': 'pfNdLM2r'}
2024-04-26 23:03:56,661 lib.lichess (lichess.py:65) DEBUG Exception: Traceback (most recent call last):
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\lichess-bot.py", line 654, in play_game
    engine.play_move(board,
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\lib\engine_wrapper.py", line 184, in play_move
    best_move = self.search(board, time_limit, can_ponder, draw_offered, best_move)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\homemade.py", line 80, in search
    prediction = lib8.predict78(model7_loaded, model8_loaded, board.fen(), move_number=counter, stochastic=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\..\chess_SL_E8_lib.py", line 730, in predict78
    eval7 = float(model7(fen_tensor, pieces_counts).to('cpu'))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EvalNet.forward() takes 2 positional arguments but 3 were given

2024-04-26 23:03:57,098 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "GET /api/bot/game/stream/pfNdLM2r HTTP/1.1" 200 None
2024-04-26 23:03:57,098 __mp_main__ (lichess-bot.py:605) DEBUG Initial state: {'id': 'pfNdLM2r', 'variant': {'key': 'standard', 'name': 'Standard', 'short': 'Std'}, 'speed': 'rapid', 'perf': {'name': 'Rapid'}, 'rated': False, 'createdAt': 1714187032154, 'white': {'id': 'checkyle', 'name': 'ChecKyle', 'title': None, 'rating': 1667, 'provisional': True}, 'black': {'id': 'ks_chessai', 'name': 'KS_ChessAI', 'title': 'BOT', 'rating': 2000, 'provisional': True}, 'initialFen': 'startpos', 'clock': {'initial': 420000, 'increment': 10000}, 'type': 'gameFull', 'state': {'type': 'gameState', 'moves': 'e2e4', 'wtime': 420000, 'btime': 420000, 'winc': 10000, 'binc': 10000, 'status': 'started'}}
2024-04-26 23:03:57,099 lib.engine_wrapper (engine_wrapper.py:68) DEBUG Starting engine: ['C:\\Users\\Kyle_Remote\\Documents\\Programs\\DS3ML3_Final_Project\\lichess-bot\\engines\\ExampleEngine']
2024-04-26 23:03:57,099 __mp_main__ (lichess-bot.py:611) DEBUG The engine for game pfNdLM2r has pid=?
2024-04-26 23:03:57,099 __mp_main__ (lichess-bot.py:614) INFO +++ https://lichess.org/pfNdLM2r/black Rapid vs ChecKyle (1667?) (pfNdLM2r)
2024-04-26 23:03:57,099 lib.conversation (conversation.py:86) INFO *** https://lichess.org/pfNdLM2r/black [player] KS_ChessAI: Hi! I'm Kyle's Chess AI. Good luck!
2024-04-26 23:03:57,100 urllib3.connectionpool (connectionpool.py:1055) DEBUG Starting new HTTPS connection (3): lichess.org:443
2024-04-26 23:03:57,611 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/pfNdLM2r/chat HTTP/1.1" 200 11
2024-04-26 23:03:57,611 lib.conversation (conversation.py:86) INFO *** https://lichess.org/pfNdLM2r/black [spectator] KS_ChessAI: Hi! I'm KS_ChessAI. Type !help for a list of commands I can respond to.
2024-04-26 23:03:57,713 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/pfNdLM2r/chat HTTP/1.1" 200 11
2024-04-26 23:03:57,713 __mp_main__ (lichess-bot.py:716) INFO 
2024-04-26 23:03:57,713 __mp_main__ (lichess-bot.py:717) INFO move: 1
2024-04-26 23:03:57,714 lib.engine_wrapper (engine_wrapper.py:687) INFO Searching for time 10 seconds for game pfNdLM2r
2024-04-26 23:03:57,716 backoff (_common.py:105) INFO Backing off play_game(...) for 0.8s (TypeError: EvalNet.forward() takes 2 positional arguments but 3 were given)
2024-04-26 23:03:57,716 lib.lichess (lichess.py:63) DEBUG Backing off 0.8 seconds after 2 tries calling function <function play_game at 0x000001D7B326C680> with args () and kwargs {'li': <lib.lichess.Lichess object at 0x000001D7B3265990>, 'control_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c0a90>, 'user_profile': {'id': 'ks_chessai', 'username': 'KS_ChessAI', 'perfs': {'bullet': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'blitz': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'rapid': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'classical': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'correspondence': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}}, 'title': 'BOT', 'createdAt': 1711486329716, 'seenAt': 1714186489523, 'playTime': {'total': 18282, 'tv': 0}, 'url': 'https://lichess.org/@/KS_ChessAI', 'count': {'all': 120, 'rated': 0, 'ai': 0, 'draw': 11, 'drawH': 11, 'loss': 92, 'lossH': 92, 'win': 17, 'winH': 17, 'bookmark': 0, 'playing': 0, 'import': 0, 'me': 0}, 'followable': True, 'following': False, 'blocking': False, 'followsYou': False}, 'config': <lib.config.Configuration object at 0x000001D7B32C2290>, 'challenge_queue': <ListProxy object, typeid 'list' at 0x1d7b32c88d0>, 'correspondence_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c8b10>, 'logging_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c8d50>, 'game_id': 'pfNdLM2r'}
2024-04-26 23:03:57,718 lib.lichess (lichess.py:65) DEBUG Exception: Traceback (most recent call last):
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\lichess-bot.py", line 654, in play_game
    engine.play_move(board,
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\lib\engine_wrapper.py", line 184, in play_move
    best_move = self.search(board, time_limit, can_ponder, draw_offered, best_move)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\homemade.py", line 80, in search
    prediction = lib8.predict78(model7_loaded, model8_loaded, board.fen(), move_number=counter, stochastic=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\..\chess_SL_E8_lib.py", line 730, in predict78
    eval7 = float(model7(fen_tensor, pieces_counts).to('cpu'))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EvalNet.forward() takes 2 positional arguments but 3 were given

2024-04-26 23:03:58,533 urllib3.connectionpool (connectionpool.py:292) DEBUG Resetting dropped connection: lichess.org
2024-04-26 23:03:59,050 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "GET /api/bot/game/stream/pfNdLM2r HTTP/1.1" 200 None
2024-04-26 23:03:59,050 __mp_main__ (lichess-bot.py:605) DEBUG Initial state: {'id': 'pfNdLM2r', 'variant': {'key': 'standard', 'name': 'Standard', 'short': 'Std'}, 'speed': 'rapid', 'perf': {'name': 'Rapid'}, 'rated': False, 'createdAt': 1714187032154, 'white': {'id': 'checkyle', 'name': 'ChecKyle', 'title': None, 'rating': 1667, 'provisional': True}, 'black': {'id': 'ks_chessai', 'name': 'KS_ChessAI', 'title': 'BOT', 'rating': 2000, 'provisional': True}, 'initialFen': 'startpos', 'clock': {'initial': 420000, 'increment': 10000}, 'type': 'gameFull', 'state': {'type': 'gameState', 'moves': 'e2e4', 'wtime': 420000, 'btime': 420000, 'winc': 10000, 'binc': 10000, 'status': 'started'}}
2024-04-26 23:03:59,051 lib.engine_wrapper (engine_wrapper.py:68) DEBUG Starting engine: ['C:\\Users\\Kyle_Remote\\Documents\\Programs\\DS3ML3_Final_Project\\lichess-bot\\engines\\ExampleEngine']
2024-04-26 23:03:59,051 __mp_main__ (lichess-bot.py:611) DEBUG The engine for game pfNdLM2r has pid=?
2024-04-26 23:03:59,051 __mp_main__ (lichess-bot.py:614) INFO +++ https://lichess.org/pfNdLM2r/black Rapid vs ChecKyle (1667?) (pfNdLM2r)
2024-04-26 23:03:59,051 lib.conversation (conversation.py:86) INFO *** https://lichess.org/pfNdLM2r/black [player] KS_ChessAI: Hi! I'm Kyle's Chess AI. Good luck!
2024-04-26 23:03:59,150 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/pfNdLM2r/chat HTTP/1.1" 200 11
2024-04-26 23:03:59,151 lib.conversation (conversation.py:86) INFO *** https://lichess.org/pfNdLM2r/black [spectator] KS_ChessAI: Hi! I'm KS_ChessAI. Type !help for a list of commands I can respond to.
2024-04-26 23:03:59,246 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/pfNdLM2r/chat HTTP/1.1" 200 11
2024-04-26 23:03:59,246 __mp_main__ (lichess-bot.py:716) INFO 
2024-04-26 23:03:59,246 __mp_main__ (lichess-bot.py:717) INFO move: 1
2024-04-26 23:03:59,247 lib.engine_wrapper (engine_wrapper.py:687) INFO Searching for time 10 seconds for game pfNdLM2r
2024-04-26 23:03:59,248 backoff (_common.py:105) INFO Backing off play_game(...) for 2.9s (TypeError: EvalNet.forward() takes 2 positional arguments but 3 were given)
2024-04-26 23:03:59,248 lib.lichess (lichess.py:63) DEBUG Backing off 2.9 seconds after 3 tries calling function <function play_game at 0x000001D7B326C680> with args () and kwargs {'li': <lib.lichess.Lichess object at 0x000001D7B3265990>, 'control_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c0a90>, 'user_profile': {'id': 'ks_chessai', 'username': 'KS_ChessAI', 'perfs': {'bullet': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'blitz': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'rapid': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'classical': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'correspondence': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}}, 'title': 'BOT', 'createdAt': 1711486329716, 'seenAt': 1714186489523, 'playTime': {'total': 18282, 'tv': 0}, 'url': 'https://lichess.org/@/KS_ChessAI', 'count': {'all': 120, 'rated': 0, 'ai': 0, 'draw': 11, 'drawH': 11, 'loss': 92, 'lossH': 92, 'win': 17, 'winH': 17, 'bookmark': 0, 'playing': 0, 'import': 0, 'me': 0}, 'followable': True, 'following': False, 'blocking': False, 'followsYou': False}, 'config': <lib.config.Configuration object at 0x000001D7B32C2290>, 'challenge_queue': <ListProxy object, typeid 'list' at 0x1d7b32c88d0>, 'correspondence_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c8b10>, 'logging_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c8d50>, 'game_id': 'pfNdLM2r'}
2024-04-26 23:03:59,249 lib.lichess (lichess.py:65) DEBUG Exception: Traceback (most recent call last):
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\lichess-bot.py", line 654, in play_game
    engine.play_move(board,
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\lib\engine_wrapper.py", line 184, in play_move
    best_move = self.search(board, time_limit, can_ponder, draw_offered, best_move)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\homemade.py", line 80, in search
    prediction = lib8.predict78(model7_loaded, model8_loaded, board.fen(), move_number=counter, stochastic=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\..\chess_SL_E8_lib.py", line 730, in predict78
    eval7 = float(model7(fen_tensor, pieces_counts).to('cpu'))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EvalNet.forward() takes 2 positional arguments but 3 were given

2024-04-26 23:04:02,174 urllib3.connectionpool (connectionpool.py:292) DEBUG Resetting dropped connection: lichess.org
2024-04-26 23:04:02,688 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "GET /api/bot/game/stream/pfNdLM2r HTTP/1.1" 200 None
2024-04-26 23:04:02,688 __mp_main__ (lichess-bot.py:605) DEBUG Initial state: {'id': 'pfNdLM2r', 'variant': {'key': 'standard', 'name': 'Standard', 'short': 'Std'}, 'speed': 'rapid', 'perf': {'name': 'Rapid'}, 'rated': False, 'createdAt': 1714187032154, 'white': {'id': 'checkyle', 'name': 'ChecKyle', 'title': None, 'rating': 1667, 'provisional': True}, 'black': {'id': 'ks_chessai', 'name': 'KS_ChessAI', 'title': 'BOT', 'rating': 2000, 'provisional': True}, 'initialFen': 'startpos', 'clock': {'initial': 420000, 'increment': 10000}, 'type': 'gameFull', 'state': {'type': 'gameState', 'moves': 'e2e4', 'wtime': 420000, 'btime': 420000, 'winc': 10000, 'binc': 10000, 'status': 'started'}}
2024-04-26 23:04:02,689 lib.engine_wrapper (engine_wrapper.py:68) DEBUG Starting engine: ['C:\\Users\\Kyle_Remote\\Documents\\Programs\\DS3ML3_Final_Project\\lichess-bot\\engines\\ExampleEngine']
2024-04-26 23:04:02,689 __mp_main__ (lichess-bot.py:611) DEBUG The engine for game pfNdLM2r has pid=?
2024-04-26 23:04:02,689 __mp_main__ (lichess-bot.py:614) INFO +++ https://lichess.org/pfNdLM2r/black Rapid vs ChecKyle (1667?) (pfNdLM2r)
2024-04-26 23:04:02,689 lib.conversation (conversation.py:86) INFO *** https://lichess.org/pfNdLM2r/black [player] KS_ChessAI: Hi! I'm Kyle's Chess AI. Good luck!
2024-04-26 23:04:02,795 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/pfNdLM2r/chat HTTP/1.1" 200 11
2024-04-26 23:04:02,796 lib.conversation (conversation.py:86) INFO *** https://lichess.org/pfNdLM2r/black [spectator] KS_ChessAI: Hi! I'm KS_ChessAI. Type !help for a list of commands I can respond to.
2024-04-26 23:04:02,896 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/pfNdLM2r/chat HTTP/1.1" 200 11
2024-04-26 23:04:02,897 __mp_main__ (lichess-bot.py:716) INFO 
2024-04-26 23:04:02,897 __mp_main__ (lichess-bot.py:717) INFO move: 1
2024-04-26 23:04:02,897 lib.engine_wrapper (engine_wrapper.py:687) INFO Searching for time 10 seconds for game pfNdLM2r
2024-04-26 23:04:02,902 backoff (_common.py:105) INFO Backing off play_game(...) for 2.0s (TypeError: EvalNet.forward() takes 2 positional arguments but 3 were given)
2024-04-26 23:04:02,902 lib.lichess (lichess.py:63) DEBUG Backing off 2.0 seconds after 4 tries calling function <function play_game at 0x000001D7B326C680> with args () and kwargs {'li': <lib.lichess.Lichess object at 0x000001D7B3265990>, 'control_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c0a90>, 'user_profile': {'id': 'ks_chessai', 'username': 'KS_ChessAI', 'perfs': {'bullet': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'blitz': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'rapid': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'classical': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'correspondence': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}}, 'title': 'BOT', 'createdAt': 1711486329716, 'seenAt': 1714186489523, 'playTime': {'total': 18282, 'tv': 0}, 'url': 'https://lichess.org/@/KS_ChessAI', 'count': {'all': 120, 'rated': 0, 'ai': 0, 'draw': 11, 'drawH': 11, 'loss': 92, 'lossH': 92, 'win': 17, 'winH': 17, 'bookmark': 0, 'playing': 0, 'import': 0, 'me': 0}, 'followable': True, 'following': False, 'blocking': False, 'followsYou': False}, 'config': <lib.config.Configuration object at 0x000001D7B32C2290>, 'challenge_queue': <ListProxy object, typeid 'list' at 0x1d7b32c88d0>, 'correspondence_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c8b10>, 'logging_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c8d50>, 'game_id': 'pfNdLM2r'}
2024-04-26 23:04:02,903 lib.lichess (lichess.py:65) DEBUG Exception: Traceback (most recent call last):
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\lichess-bot.py", line 654, in play_game
    engine.play_move(board,
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\lib\engine_wrapper.py", line 184, in play_move
    best_move = self.search(board, time_limit, can_ponder, draw_offered, best_move)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\homemade.py", line 80, in search
    prediction = lib8.predict78(model7_loaded, model8_loaded, board.fen(), move_number=counter, stochastic=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\..\chess_SL_E8_lib.py", line 730, in predict78
    eval7 = float(model7(fen_tensor, pieces_counts).to('cpu'))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EvalNet.forward() takes 2 positional arguments but 3 were given

2024-04-26 23:04:04,899 urllib3.connectionpool (connectionpool.py:292) DEBUG Resetting dropped connection: lichess.org
2024-04-26 23:04:05,410 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "GET /api/bot/game/stream/pfNdLM2r HTTP/1.1" 200 None
2024-04-26 23:04:05,411 __mp_main__ (lichess-bot.py:605) DEBUG Initial state: {'id': 'pfNdLM2r', 'variant': {'key': 'standard', 'name': 'Standard', 'short': 'Std'}, 'speed': 'rapid', 'perf': {'name': 'Rapid'}, 'rated': False, 'createdAt': 1714187032154, 'white': {'id': 'checkyle', 'name': 'ChecKyle', 'title': None, 'rating': 1667, 'provisional': True}, 'black': {'id': 'ks_chessai', 'name': 'KS_ChessAI', 'title': 'BOT', 'rating': 2000, 'provisional': True}, 'initialFen': 'startpos', 'clock': {'initial': 420000, 'increment': 10000}, 'type': 'gameFull', 'state': {'type': 'gameState', 'moves': 'e2e4', 'wtime': 420000, 'btime': 420000, 'winc': 10000, 'binc': 10000, 'status': 'started'}}
2024-04-26 23:04:05,411 lib.engine_wrapper (engine_wrapper.py:68) DEBUG Starting engine: ['C:\\Users\\Kyle_Remote\\Documents\\Programs\\DS3ML3_Final_Project\\lichess-bot\\engines\\ExampleEngine']
2024-04-26 23:04:05,411 __mp_main__ (lichess-bot.py:611) DEBUG The engine for game pfNdLM2r has pid=?
2024-04-26 23:04:05,411 __mp_main__ (lichess-bot.py:614) INFO +++ https://lichess.org/pfNdLM2r/black Rapid vs ChecKyle (1667?) (pfNdLM2r)
2024-04-26 23:04:05,411 lib.conversation (conversation.py:86) INFO *** https://lichess.org/pfNdLM2r/black [player] KS_ChessAI: Hi! I'm Kyle's Chess AI. Good luck!
2024-04-26 23:04:05,518 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/pfNdLM2r/chat HTTP/1.1" 200 11
2024-04-26 23:04:05,518 lib.conversation (conversation.py:86) INFO *** https://lichess.org/pfNdLM2r/black [spectator] KS_ChessAI: Hi! I'm KS_ChessAI. Type !help for a list of commands I can respond to.
2024-04-26 23:04:05,616 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/pfNdLM2r/chat HTTP/1.1" 200 11
2024-04-26 23:04:05,617 __mp_main__ (lichess-bot.py:716) INFO 
2024-04-26 23:04:05,617 __mp_main__ (lichess-bot.py:717) INFO move: 1
2024-04-26 23:04:05,618 lib.engine_wrapper (engine_wrapper.py:687) INFO Searching for time 10 seconds for game pfNdLM2r
2024-04-26 23:04:05,620 backoff (_common.py:105) INFO Backing off play_game(...) for 9.7s (TypeError: EvalNet.forward() takes 2 positional arguments but 3 were given)
2024-04-26 23:04:05,621 lib.lichess (lichess.py:63) DEBUG Backing off 9.7 seconds after 5 tries calling function <function play_game at 0x000001D7B326C680> with args () and kwargs {'li': <lib.lichess.Lichess object at 0x000001D7B3265990>, 'control_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c0a90>, 'user_profile': {'id': 'ks_chessai', 'username': 'KS_ChessAI', 'perfs': {'bullet': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'blitz': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'rapid': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'classical': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'correspondence': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}}, 'title': 'BOT', 'createdAt': 1711486329716, 'seenAt': 1714186489523, 'playTime': {'total': 18282, 'tv': 0}, 'url': 'https://lichess.org/@/KS_ChessAI', 'count': {'all': 120, 'rated': 0, 'ai': 0, 'draw': 11, 'drawH': 11, 'loss': 92, 'lossH': 92, 'win': 17, 'winH': 17, 'bookmark': 0, 'playing': 0, 'import': 0, 'me': 0}, 'followable': True, 'following': False, 'blocking': False, 'followsYou': False}, 'config': <lib.config.Configuration object at 0x000001D7B32C2290>, 'challenge_queue': <ListProxy object, typeid 'list' at 0x1d7b32c88d0>, 'correspondence_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c8b10>, 'logging_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c8d50>, 'game_id': 'pfNdLM2r'}
2024-04-26 23:04:05,621 lib.lichess (lichess.py:65) DEBUG Exception: Traceback (most recent call last):
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\lichess-bot.py", line 654, in play_game
    engine.play_move(board,
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\lib\engine_wrapper.py", line 184, in play_move
    best_move = self.search(board, time_limit, can_ponder, draw_offered, best_move)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\homemade.py", line 80, in search
    prediction = lib8.predict78(model7_loaded, model8_loaded, board.fen(), move_number=counter, stochastic=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\..\chess_SL_E8_lib.py", line 730, in predict78
    eval7 = float(model7(fen_tensor, pieces_counts).to('cpu'))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EvalNet.forward() takes 2 positional arguments but 3 were given

2024-04-26 23:04:15,287 urllib3.connectionpool (connectionpool.py:292) DEBUG Resetting dropped connection: lichess.org
2024-04-26 23:04:15,792 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "GET /api/bot/game/stream/pfNdLM2r HTTP/1.1" 200 None
2024-04-26 23:04:15,793 __mp_main__ (lichess-bot.py:605) DEBUG Initial state: {'id': 'pfNdLM2r', 'variant': {'key': 'standard', 'name': 'Standard', 'short': 'Std'}, 'speed': 'rapid', 'perf': {'name': 'Rapid'}, 'rated': False, 'createdAt': 1714187032154, 'white': {'id': 'checkyle', 'name': 'ChecKyle', 'title': None, 'rating': 1667, 'provisional': True}, 'black': {'id': 'ks_chessai', 'name': 'KS_ChessAI', 'title': 'BOT', 'rating': 2000, 'provisional': True}, 'initialFen': 'startpos', 'clock': {'initial': 420000, 'increment': 10000}, 'type': 'gameFull', 'state': {'type': 'gameState', 'moves': 'e2e4', 'wtime': 420000, 'btime': 420000, 'winc': 10000, 'binc': 10000, 'status': 'started'}}
2024-04-26 23:04:15,793 lib.engine_wrapper (engine_wrapper.py:68) DEBUG Starting engine: ['C:\\Users\\Kyle_Remote\\Documents\\Programs\\DS3ML3_Final_Project\\lichess-bot\\engines\\ExampleEngine']
2024-04-26 23:04:15,793 __mp_main__ (lichess-bot.py:611) DEBUG The engine for game pfNdLM2r has pid=?
2024-04-26 23:04:15,793 __mp_main__ (lichess-bot.py:614) INFO +++ https://lichess.org/pfNdLM2r/black Rapid vs ChecKyle (1667?) (pfNdLM2r)
2024-04-26 23:04:15,794 lib.conversation (conversation.py:86) INFO *** https://lichess.org/pfNdLM2r/black [player] KS_ChessAI: Hi! I'm Kyle's Chess AI. Good luck!
2024-04-26 23:04:15,795 urllib3.connectionpool (connectionpool.py:292) DEBUG Resetting dropped connection: lichess.org
2024-04-26 23:04:16,350 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/pfNdLM2r/chat HTTP/1.1" 200 11
2024-04-26 23:04:16,351 lib.conversation (conversation.py:86) INFO *** https://lichess.org/pfNdLM2r/black [spectator] KS_ChessAI: Hi! I'm KS_ChessAI. Type !help for a list of commands I can respond to.
2024-04-26 23:04:16,449 urllib3.connectionpool (connectionpool.py:549) DEBUG https://lichess.org:443 "POST /api/bot/game/pfNdLM2r/chat HTTP/1.1" 200 11
2024-04-26 23:04:16,450 __mp_main__ (lichess-bot.py:716) INFO 
2024-04-26 23:04:16,450 __mp_main__ (lichess-bot.py:717) INFO move: 1
2024-04-26 23:04:16,450 lib.engine_wrapper (engine_wrapper.py:687) INFO Searching for time 10 seconds for game pfNdLM2r
2024-04-26 23:04:16,454 backoff (_common.py:105) INFO Backing off play_game(...) for 9.3s (TypeError: EvalNet.forward() takes 2 positional arguments but 3 were given)
2024-04-26 23:04:16,454 lib.lichess (lichess.py:63) DEBUG Backing off 9.3 seconds after 6 tries calling function <function play_game at 0x000001D7B326C680> with args () and kwargs {'li': <lib.lichess.Lichess object at 0x000001D7B3265990>, 'control_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c0a90>, 'user_profile': {'id': 'ks_chessai', 'username': 'KS_ChessAI', 'perfs': {'bullet': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'blitz': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'rapid': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'classical': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}, 'correspondence': {'games': 0, 'rating': 2000, 'rd': 500, 'prog': 0, 'prov': True}}, 'title': 'BOT', 'createdAt': 1711486329716, 'seenAt': 1714186489523, 'playTime': {'total': 18282, 'tv': 0}, 'url': 'https://lichess.org/@/KS_ChessAI', 'count': {'all': 120, 'rated': 0, 'ai': 0, 'draw': 11, 'drawH': 11, 'loss': 92, 'lossH': 92, 'win': 17, 'winH': 17, 'bookmark': 0, 'playing': 0, 'import': 0, 'me': 0}, 'followable': True, 'following': False, 'blocking': False, 'followsYou': False}, 'config': <lib.config.Configuration object at 0x000001D7B32C2290>, 'challenge_queue': <ListProxy object, typeid 'list' at 0x1d7b32c88d0>, 'correspondence_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c8b10>, 'logging_queue': <AutoProxy[Queue] object, typeid 'Queue' at 0x1d7b32c8d50>, 'game_id': 'pfNdLM2r'}
2024-04-26 23:04:16,455 lib.lichess (lichess.py:65) DEBUG Exception: Traceback (most recent call last):
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\backoff\_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\lichess-bot.py", line 654, in play_game
    engine.play_move(board,
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\lib\engine_wrapper.py", line 184, in play_move
    best_move = self.search(board, time_limit, can_ponder, draw_offered, best_move)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\homemade.py", line 80, in search
    prediction = lib8.predict78(model7_loaded, model8_loaded, board.fen(), move_number=counter, stochastic=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\lichess-bot\..\chess_SL_E8_lib.py", line 730, in predict78
    eval7 = float(model7(fen_tensor, pieces_counts).to('cpu'))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Kyle_Remote\Documents\Programs\DS3ML3_Final_Project\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EvalNet.forward() takes 2 positional arguments but 3 were given

2024-04-26 23:04:16,289 __main__ (lichess-bot.py:71) DEBUG Received SIGINT. Terminating client.
2024-04-26 23:04:18,493 __main__ (lichess-bot.py:71) DEBUG Received SIGINT. Terminating client.
